// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Vsm6jJp4nVymKoUqFo7t48SecdQm7Fg',
    appId: '1:630411152284:web:ba705f1b490af1b2359659',
    messagingSenderId: '630411152284',
    projectId: 'aguasol-c26f8',
    authDomain: 'aguasol-c26f8.firebaseapp.com',
    storageBucket: 'aguasol-c26f8.appspot.com',
    measurementId: 'G-86Y9YK0LFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXxwtanT07WsZ63mcyok3J0yshXxi6CXE',
    appId: '1:630411152284:android:4f5239a277e11d84359659',
    messagingSenderId: '630411152284',
    projectId: 'aguasol-c26f8',
    storageBucket: 'aguasol-c26f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBAE7OunnUIDQamv3RvGrmSCDlMJg4iK0',
    appId: '1:630411152284:ios:f1404291718779ed359659',
    messagingSenderId: '630411152284',
    projectId: 'aguasol-c26f8',
    storageBucket: 'aguasol-c26f8.appspot.com',
    iosClientId: '630411152284-a5fqlh6k36gug6uniar0iv577c6iajad.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBAE7OunnUIDQamv3RvGrmSCDlMJg4iK0',
    appId: '1:630411152284:ios:09ade5ce38cb5a40359659',
    messagingSenderId: '630411152284',
    projectId: 'aguasol-c26f8',
    storageBucket: 'aguasol-c26f8.appspot.com',
    iosClientId: '630411152284-h7lcsd74djjv0uveumaoi4qge48443gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinal.RunnerTests',
  );
}
